name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.build }} Build

    strategy:
      matrix:
        build: ["Debug", "Release"]
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
      CI: true

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: ${{ matrix.build }} Build with Gradle
      run: ./gradlew assemble${{ matrix.build }} --warning-mode all

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: flexbooru_pro_patch
        path: android/build/outputs/apk/*/*.apk
        if-no-files-found: ignore
        retention-days: 90
