name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process" -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport
      CI: true

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'cf18bca267c0089572eadea692d9b4440df63224'
      
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: ./gradlew assemble -x lint -x test --warning-mode all

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: flexbooru_pro_patch
        path: android/build/outputs/apk/**/*.apk
        if-no-files-found: ignore
        retention-days: 1
